---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	smart_router(smart_router)
	planner(planner)
	executor(executor)
	executor_with_approval(executor_with_approval)
	step_complete(step_complete)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> smart_router;
	executor -.-> step_complete;
	executor -.-> tools;
	executor_with_approval -. &nbsp;end&nbsp; .-> __end__;
	executor_with_approval -.-> step_complete;
	executor_with_approval -.-> tools;
	planner -. &nbsp;end&nbsp; .-> __end__;
	planner -.-> executor;
	planner -.-> executor_with_approval;
	smart_router -. &nbsp;end&nbsp; .-> __end__;
	smart_router -.-> planner;
	step_complete -. &nbsp;end&nbsp; .-> __end__;
	step_complete -.-> executor;
	step_complete -.-> executor_with_approval;
	tools -.-> executor;
	tools -.-> executor_with_approval;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
