/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    ApiService: {
      service: string;
      type: "sst.aws.Service";
      url: string;
    };
    ApiVpc: {
      type: "sst.aws.Vpc";
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
